framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: ~
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 31536000
    #esi: true
    #fragments: true
    php_errors:
        log: true
    templating:
        engines: [ 'twig' ]
    serializer:
        enable_annotations: true
