vich_uploader:
    db_driver: orm
    mappings:
        way_point_image:
            uri_prefix:         /images/way_points
            upload_destination: '%kernel.project_dir%/public/images/way_points'
            inject_on_load:     false # should the file be injected into the uploadable entity when it is loaded from the data store
            delete_on_update:   true  # should the file be deleted when a new file is uploaded
            delete_on_remove:   true  # should the file be deleted when a new file is removed
