global_exclude_dirs:
    - vendor
    - vendors
    - test
    - tests
    - Tests
    - lib/vendor
    - web/js

exclude_patterns:
    - web/config.php
    - web/app_*.php
    - src/DataFixtures/ORM/user.yml
