preset: symfony

risky: false

disabled:
    - blank_line_after_opening_tag

finder:
    exclude:
        - "app/DoctrineMigrations"
        - "var"
    name:
        - "*.php"
    not-name:
        - "*Stub.php"
    depth:
        - "< 4"
