preset: symfony

disabled:
  - blank_line_before_declare

risky: true

finder:
  exclude:
    - "app/DoctrineMigrations"
    - "var"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  depth:
    - "< 4"
