language: php

node_js:
 - "node"
 - "8"

cache:
  yarn: true
  directories:
    - node_modules

dist: trusty
sudo: required

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - yarn install
  - node_modules/.bin/encore production
  - composer install -vv
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console hautelook_alice:doctrine:fixtures:load --no-interaction --env=test

script:
  - ./vendor/bin/phpunit
