services:
  - docker

dist: xenial
os: linux
language: php

before_script:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - cp .env.dist .env
  - cp docker-compose.override.yml.dist docker-compose.override.yml
  - docker network create swapp-test
  - docker-compose -f docker-compose.travis.yml -f docker-compose.yml build web
  - docker-compose -f docker-compose.travis.yml -f docker-compose.yml up --detach

script:
  - sleep 30
  - docker-compose exec --user=docker web printenv || true
  - docker-compose logs web || true
  - docker-compose -f docker-compose.travis.yml -f docker-compose.yml exec --user=docker web composer qa-ci || true

# get access to debug screenshots from ci
deploy:
  provider: releases
  token:
    secure: "XaVbbAp4PybuVYCPkadfGiwJHtS5XIAxTAYVfb6w6ibu+v00QXZlsx1rPB6XNkQJL1t/qQt4LhVf7QduGRz0u2JEFv1iLc4hHJpiE+LzsPWP2ub6+sN+/qir33Ybhk0rXksRAA9A8wKoKz6JOzTD90h97OLPvCrLIOrPFvSGMgsQ0fTN4DHLhFz+DqfDVghFwjXD8sXbBnSA7l5Jch+W55qemMaEkOikKGMUHZTfiz1a0LZcw4ACWVCm51sbxFEsBhfcsehXac/WjQQeA7mrVLzUlH7sYwP54xfTW5A12/97zVmE5LPzFq2jLYsSjExCHaq5w5WvtC8EaVChpDV+cqglkBE4upx0tnvZjboF0T9PXKua3ex9O7WZXtxZKycsdJJMws0wP/NpsHSOjtDmjidDLwXOaMcMpB1jpACicn/wOFOEk1x/7VSRXlkvkYp0icc/Tj8e3gRQneBrEkzBfHehrVPauWalF5wq1pC1blxcksYGZn3NMbl2252ed8d5vpKBArgaTPInMVxzpbhMzxrXTUHUE/eXsagz7LfFGIZ4yJFcO5AwgEd7PxKWj50NaeBmDHyJKC2ABxmUPEmFnK7ADrFDLCzpHgH9KLYk+DPA3MVwKmEOglHQRmaRMu8iGyfxzruXDFKXuUuUyDQr/RVggHi/5jr9Xff7xFCh+RY="
  file_glob: true
  file:
    - volumes/web/images/screenshots/*
    - volumes/web/apache-logs/access.log
    - volumes/web/apache-logs/error.log
    - volumes/web/symfony-logs/*
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    tags: false
    all_branches: true

after_failure:
  - ls -la
  - ls -la volumes/*
  - ls -la volumes/web/*
