language: php

cache:
  yarn: true
  directories:
    - node_modules

php:
  - 7.4

addons:
  chrome: stable

env:
  - TRAVIS_NODE_VERSION="12.8.0"

before_install: echo "extension = zip.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - cp .env.travis .env
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node -v
  - yarn install
  - composer install -vv
  - yarn encore production
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console hautelook:fixtures:load --no-interaction --env=test

script:
  - composer qa-ci
