version: "3"
services:

  web:
    env_file: .env.docker
    volumes:
      - .:/var/www/html
    networks:
      - swapp
    command: /init-project.sh
    restart: "always"
    tty: true
    container_name: swapp
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - swapp
    restart: "always"

volumes:
  mysql_data:

networks:
  swapp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
