version: "3"
services:

  web:
    env_file: .env.docker
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - 8082:80
      - 8083:8083
    restart: "no"
    environment:
      HOST_UID: ${HOST_UID} # set in ~/.bashrc
      HOST_GID: ${HOST_GID} # set in ~/.bashrc
      CONTAINER_USER: docker
      CONTAINER_GROUP: docker

  mysql:
    ports:
      - 8875:3306
    restart: "no"

networks:
  swapp:
    driver: bridge
