version: "3"
services:

  web:
    build:
      context: .docker/web
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "8082:8082"
      - "443:443"
      - "4445:4445"
    networks:
      - swapp
    command: /init-project.sh
    environment:
      PHP_XDEBUG_ENABLED: 0
      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1
      PHP_IDE_CONFIG: serverName=swapp-docker-container
    tty: true
    container_name: swapp
    depends_on:
      - mysql
      - node-chrome
      - node-firefox

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - swapp
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: swapp
       MYSQL_USER: swapp
       MYSQL_PASSWORD: pa$$word

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - swapp

  node-firefox:
    image: selenium/node-firefox-debug
    networks:
      - swapp
    ports:
      - "5900:5900"
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  node-chrome:
    image: selenium/node-chrome-debug
    networks:
      - swapp
    ports:
      - "5901:5900"
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

volumes:
  mysql_data:

networks:
  swapp:
    driver: bridge
