version: "3"
services:

  web:
    networks:
      - swapp
    command: /init-project.sh
    restart: "always"
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - swapp
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:

volumes:
  mysql_data:

networks:
  swapp:
    driver: bridge
