/**
 * Vorgefilterte und vorsortierte Liste der erlaubten Tag-Farben.
 *
 * Vorher wurde die komplette `color_library`-NPM-Lib importiert (~158 KB im
 * Tags-Chunk: 147 HTML-Farben + RAL- und Pantone-Tabellen, alles in einem
 * CommonJS-Block ohne Tree-Shaking-Moeglichkeit). Genutzt wurden davon nur die
 * HTML-Farben, von denen ein Grossteil per `name.toLowerCase().includes(...)`
 * wieder ausgeblendet wurde.
 *
 * Da der Filter rein statisch ist, wurde er einmal angewendet und das Ergebnis
 * (75 Farben, sortiert nach RGB-Wertigkeit wie zuvor) hier persistiert. Damit
 * faellt color_library als Dependency komplett weg.
 */
export const availableColors: ReadonlyArray<{ name: string }> = [
    { name: "Navy" },
    { name: "MediumBlue" },
    { name: "MidnightBlue" },
    { name: "Blue" },
    { name: "Indigo" },
    { name: "Teal" },
    { name: "Maroon" },
    { name: "DarkSlateBlue" },
    { name: "Lime" },
    { name: "Purple" },
    { name: "SaddleBrown" },
    { name: "DarkTurquoise" },
    { name: "Brown" },
    { name: "RoyalBlue" },
    { name: "FireBrick" },
    { name: "DeepSkyBlue" },
    { name: "OliveDrab" },
    { name: "Olive" },
    { name: "SteelBlue" },
    { name: "Sienna" },
    { name: "SlateBlue" },
    { name: "Crimson" },
    { name: "CadetBlue" },
    { name: "DarkOrchid" },
    { name: "Aqua" },
    { name: "MediumSlateBlue" },
    { name: "CornflowerBlue" },
    { name: "Turquoise" },
    { name: "Chocolate" },
    { name: "MediumPurple" },
    { name: "MediumAquaMarine" },
    { name: "Chartreuse" },
    { name: "MediumOrchid" },
    { name: "Peru" },
    { name: "DeepPink" },
    { name: "RosyBrown" },
    { name: "GoldenRod" },
    { name: "Fuchsia" },
    { name: "Tomato" },
    { name: "DarkKhaki" },
    { name: "DarkOrange" },
    { name: "SkyBlue" },
    { name: "Orchid" },
    { name: "Orange" },
    { name: "Coral" },
    { name: "Aquamarine" },
    { name: "Salmon" },
    { name: "DarkSalmon" },
    { name: "Tan" },
    { name: "LightSteelBlue" },
    { name: "Silver" },
    { name: "HotPink" },
    { name: "SandyBrown" },
    { name: "Gold" },
    { name: "Plum" },
    { name: "PowderBlue" },
    { name: "LightSalmon" },
    { name: "Thistle" },
    { name: "Yellow" },
    { name: "Khaki" },
    { name: "Gainsboro" },
    { name: "LightPink" },
    { name: "PaleGoldenRod" },
    { name: "Pink" },
    { name: "Wheat" },
    { name: "Lavender" },
    { name: "Bisque" },
    { name: "Beige" },
    { name: "MistyRose" },
    { name: "PapayaWhip" },
    { name: "Linen" },
    { name: "LemonChiffon" },
    { name: "Azure" },
    { name: "LavenderBlush" },
    { name: "Ivory" },
];
