<?php

namespace AppBundle\Repository;

use AppBundle\Value\AgeRange;
use Doctrine\ORM\EntityRepository;

/**
 * DoctrineORMAgeRangeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DoctrineORMAgeRangeRepository extends EntityRepository implements AgeRangeRepositoryInterface
{
    /**
     * @param AgeRange $range
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(AgeRange $range)
    {
        $this->_em->persist($range);
        $this->_em->flush();
    }

    /**
     * @param $id
     * @return AgeRange
     */
    public function getRange($id)
    {
        return parent::findOneBy(['id' => $id]);
    }
}
