easy_admin:
    site_name: Swapp -<br>Streetworker App
    list:
        actions:
            - { name: 'show', icon: 'search', 'label': false }
            - { name: 'edit', icon: 'pencil', 'label': false }
    entities:
        Team:
            class: AppBundle\Entity\Team
            label: eadmin.team.label
            list:
                title: eadmin.team.list.title
                fields:
                  - 'id'
                  - 'name'
                  - 'users'
            form:
                fields:
                  - 'name'
                  - 'users'
            edit:
                fields:
                    - 'name'
                    - { property: 'users',type_options: { by_reference: false }}
            show:
                fields:
                  - 'name'
                  - 'users'
        Walk:
            class: AppBundle\Entity\Walk
            label: eadmin.walk.label
            form:
                fields:
                    - 'name'
                    - { property: 'startTime', type: 'datetime' }
                    - { property: 'endTime', type: 'datetime' }
                    - 'wayPoints'
                    - 'walkReflection'
                    - 'rating'
                    - 'systemicQuestion'
                    - { property: 'systemicAnswer', type: 'textarea' }
            list:
                title: eadmin.walk.list.title
                fields:
                    - 'name'
                    - { property: 'startTime', type: 'datetime' }
                    - { property: 'endTime', type: 'datetime' }
                    - 'wayPoints'
                    - 'walkReflection'
                    - 'rating'
                    - 'systemicQuestion'
        WayPoint:
            class: AppBundle\Entity\WayPoint
            label: eadmin.way-point.label
            list:
                title: eadmin.way_point.list.title
                fields:
                    - 'locationName'
                    - 'malesChildCount'
                    - 'femalesChildCount'
                    - 'note'
                    - 'isMeeting'
                    - 'walk'
            form:
                title: eadmin.way_point.edit.title
            show:
                title: eadmin.way_point.show.title
        Tag:
            class: AppBundle\Entity\Tag
            label: eadmin.tag.label
            list:
                title: eadmin.tag.list.title
        User:
            class: AppBundle\Entity\User
            label: eadmin.user.label
            list:
                title: eadmin.user.list.title
                fields:
                    - id
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - locked
                    - roles
                    - teams
                    - walks
            form:
                fields:
                    - username
                    - email
                    - plainPassword
                    - roles
                    - teams
                    - walks
                    - enabled
        Guest:
            class: AppBundle\Entity\Guest
            label: eadmin.guest.label
            list:
                title: eadmin.guest.list.title
        SystemicQuestion:
            class: AppBundle\Entity\SystemicQuestion
            label: eadmin.systemic-question.label
            list:
                title: eadmin.systemic-question.list.title
            form:
                fields:
                    - 'id'
                    - { property: 'question', type: 'textarea' }
                    - 'walks'
