imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: admin.yml }
    - { resource: services.yml }

bugsnag:
    api_key: '%bugsnag.api_key%'
    enabled_stages: [prod]
    notify_stages: [production]
    app_version: '%bugsnag.app_version%'
    user: app.bugsnag_user

framework:
    #esi:             ~
    translator:      { fallbacks: ["de"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "de"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_lifetime: 31536000
    fragments:       ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'bootstrap_4_layout.html.twig'
    strict_variables: "%kernel.debug%"
    paths:
        - "%kernel.root_dir%/../templates"
        - "%kernel.root_dir%/../vendor/ninsuo/symfony-collection"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: 5.7 # your database server version here
        charset: utf8mb4
        default_table_options:
            options:
            #                        "SET NAMES 'UTF8' COLLATE 'utf8_unicode_ci'"
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

doctrine_migrations:
    dir_name: '%kernel.root_dir%/DoctrineMigrations'
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

stof_doctrine_extensions:
    default_locale: de_DE
    orm:
        default:
            tree: true
            softdeleteable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

vich_uploader:
    db_driver: orm
    mappings:
        way_point_image:
            uri_prefix:         /images/way_points
            upload_destination: '%kernel.root_dir%/../web/images/way_points'
            inject_on_load:     false # should the file be injected into the uploadable entity when it is loaded from the data store
            delete_on_update:   true  # should the file be deleted when a new file is uploaded
            delete_on_remove:   true  # should the file be deleted when a new file is removed

sensio_framework_extra:
    router:
        annotations: false

webpack_encore:
    output_path: '%kernel.project_dir%/web/build'
