imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
            # handler_id set to null will use default session handler from php.ini
            handler_id:  ~
            storage_id: session.storage.filesystem
            name: MOCKSESSID
    profiler:
        collect: false

liip_functional_test:
    cache_sqlite_db: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:    '%kernel.cache_dir%/test.db'

security:
    firewalls:
        main:
            http_basic: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
