app:
    resource: "../../src/AppBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "../../src/AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /eadmin

_fos:
    resource: routing_fos.yml

_hwio:
    resource: routing_hwio.yml

home:
    path: /
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: walk_home_screen
        permanent: false
        ignoreAttributes: true
