admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /eadmin

_fos:
    resource: routing_fos.yml

controller_as_a_service_example:
    path: /caas
    defaults: { _controller: app.controller.controller_as_a_service:exampleAction }

param_converter_example:
    path: /pc/{name}/{anotherName}
    defaults: { _controller: app.controller.controller_as_a_service:paramConverterAction }

walk_home_screen:
    path: /walks
    defaults: { _controller: app.controller.walks_controller:homeScreenAction }

walk_show:
    path: /walk/{walkId}
    defaults: { _controller: app.controller.walks_controller:showAction }

tag_home_screen:
    path: /tag
    defaults: { _controller: app.controller.tag_controller:homeScreenAction }

tag_create_form:
    path: /createtag
    defaults: { _controller: app.controller.tag_controller:createTagFormAction }

tag_create:
   path: /tagcreated
   defaults: { _controller: app.controller.tag_controller:createTagAction}

walk_create_form:
   path: /createwalk/{walkId}
   defaults: { _controller: app.controller.walks_controller:createWalkFormAction }

walk_create:
  path: /walkcreated
  defaults: { _controller: app.controller.walks_controller:createWalkAction}

way_point_show:
    path: /waypoint/{wayPointId}
    defaults: { _controller: app.controller.waypoint_controller:showAction }

way_point_create:
    path: /waypointcreated/{walkId}
    defaults: { _controller: app.controller.waypoint_controller:createWayPointAction}

start_walk_with_way_point:
   path: /startWalkWithTeam/{teamId}
   defaults: { _controller: app.controller.waypoint_controller:startWalkWithWayPointAction }

data_table_way_point:
   path: /table/waypoint
   defaults: { _controller: app.controller.waypoint_controller:dataTableAction }

update_walk_with_way_point:
   path: /addWayPointToWalk/{walkId}
   defaults: { _controller: app.controller.waypoint_controller:updateWalkWithWayPointAction }
