app:
    resource: "../../src/Controller/"
    type:     annotation

easy_admin_bundle:
    resource: "../../src/Controller/AdminController.php"
    type:     annotation
    prefix:   /eadmin

home:
    path: /
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: walk_home_screen
        permanent: false
        ignoreAttributes: true
