admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /eadmin

_fos:
    resource: routing_fos.yml

controller_as_a_service_example:
    path: /caas
    defaults: { _controller: app.controller.controller_as_a_service:exampleAction }

param_converter_example:
    path: /pc/{name}/{anotherName}
    defaults: { _controller: app.controller.controller_as_a_service:paramConverterAction }

walk_homescreen:
    path: /walks
    defaults: { _controller: app.controller.walks_controller:homeScreenAction }

walk_show:
    path: /walk/{id}
    defaults: { _controller: app.controller.walks_controller:showAction }

tag_testscreen:
    path: /tag
    defaults: { _controller: app.controller.tag_controller:homeScreenAction }

tag_createform:
    path: /createtag
    defaults: { _controller: app.controller.tag_controller:createTagFormAction }

tag_create:
   path: /tagcreated
   defaults: { _controller: app.controller.tag_controller:createTagAction}

waypoint_testscreen:
    path: /waypoint
    defaults: { _controller: app.controller.waypoint_controller:homeScreenAction }
