admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

controller_as_a_service_example:
    path: /caas
    defaults: { _controller: app.controller.controller_as_a_service:exampleAction }

param_converter_example:
    path: /pc/{name}/{anotherName}
    defaults: { _controller: app.controller.controller_as_a_service:paramConverterAction }
