admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

controller_as_a_service_example:
    path: /caas
    defaults: { _controller: app.controller.controller_as_a_service:exampleAction }

param_converter_example:
    path: /pc/{name}/{anotherName}
    defaults: { _controller: app.controller.controller_as_a_service:paramConverterAction }

walk_homescreen:
    path: /walks
    defaults: { _controller: app.controller.walks_controller:homeScreenAction }

tag_testcreen:
    path: /tag
    defaults: { _controller: app.controller.tag_controller:homeScreenAction }

waypoint_testscreen:
    path: /waypoint
    defaults: { _controller: app.controller.waypoint_controller:homeScreenAction }