services:
    app.admin.walk:
          class: AppBundle\Admin\WalkAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: swapp_tables, label: walk }
          arguments: [null, AppBundle\Entity\Walk, AppBundle:WalkAdmin]

    app.admin.way_point:
          class: AppBundle\Admin\WayPointAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: swapp_tables, label: way_point }
          arguments: [null, AppBundle\Entity\WayPoint, AppBundle:WayPointAdmin]

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: swapp_tables, label: user }
        arguments: [null, AppBundle\Entity\User, AppBundle:UserAdmin]

    app.admin.tag:
        class: AppBundle\Admin\TagAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: swapp_tables, label: tag }
        arguments: [null, AppBundle\Entity\Tag, AppBundle:TagAdmin]
