services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    AppBundle\Repository\:
        resource: '../../src/AppBundle/Repository/*'
#        exclude: '../src/Repository'

#    app.factory_service.systemic_question_repository:
#        class: AppBundle\Repository\SystemicQuestionRepositoryInterface
#        factory: ['@doctrine', getRepository]
#        arguments:
#            - 'AppBundle:SystemicQuestion'
#
#    app.factory_service.walk_repository:
#        class: AppBundle\Repository\WalkRepositoryInterface
#        factory: ['@doctrine', getRepository]
#        arguments:
#            - 'AppBundle:Walk'
#
#    app.factory_service.way_point_repository:
#        class: AppBundle\Repository\WayPointRepositoryInterface
#        factory: ['@doctrine', getRepository]
#        arguments:
#            - 'AppBundle:WayPoint'
#
#    app.factory_service.user_repository:
#        class: AppBundle\Repository\UserRepositoryInterface
#        factory: ['@doctrine', getRepository]
#        arguments:
#            - 'AppBundle:User'
#
#    app.factory_service.tag_repository:
#        class: AppBundle\Repository\TagRepositoryInterface
#        factory: ['@doctrine', getRepository]
#        arguments:
#            - 'AppBundle:Tag'
#
#    app.factory_service.team_repository:
#        class: AppBundle\Repository\TeamRepositoryInterface
#        factory: ['@doctrine', getRepository]
#        arguments:
#            - 'AppBundle:Team'
