imports:
    - { resource: services_command.yml }
    - { resource: services_controller.yml }
    - { resource: services_form_type.yml }
    - { resource: services_param_converter.yml }
    - { resource: services_repository.yml }
    - { resource: services_twig.yml }

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# dummy service for controller as a service
    app.controller.controller_as_a_service:
        class: AppBundle\Controller\ControllerAsAServiceController
        arguments: ['@templating']

# dummy service for param converter
    app.param_converter.example:
        class: AppBundle\ParamConverter\ExampleParamConverter
        arguments: []
        tags:
            - { name: request.param_converter, converter: example, priority: 10 }
