# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

imports:
    - { resource: services_admin.yml }

parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.controller.controller_as_a_service:
        class: AppBundle\Controller\ControllerAsAServiceController
        arguments: [@templating]

    app.param_converter.example:
        class: AppBundle\ParamConverter\ExampleParamConverter
        arguments: []
        tags:
            - { name: request.param_converter, converter: example, priority: 10 }

    app.param_converter.flash_bag:
        class: AppBundle\ParamConverter\FlashBagParamConverter
        arguments:
          - @session
        tags:
            - { name: request.param_converter, converter: flash_bag, priority: 10 }

    app.controller.walks_controller:
      class: AppBundle\Controller\WalksController
      arguments: [@templating, @app.factory_service.walk_repository]

    app.controller.tag_controller:
      class: AppBundle\Controller\TagController
      arguments: [@templating, @app.factory_service.tag_repository, @service_container]

    app.controller.waypoint_controller:
      class: AppBundle\Controller\WayPointController
      arguments: [@templating, @app.factory_service.waypoint_repository]

    app.factory_service.walk_repository:
        class: AppBundle\Repository\WalkRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Walk

    app.factory_service.waypoint_repository:
        class: AppBundle\Repository\WayPointRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\WayPoint

    app.factory_service.tag_repository:
        class: AppBundle\Repository\TagRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Tag
