api_platform:
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        csv: [ 'text/csv' ]
        html: [ 'text/html' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Dto']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # Default value
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 10
        normalization_context:
            skip_null_values: false
