# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        way-point.image.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/images/way_points'
