security:
    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        confirmation-token:
            pattern: ^/api/users/is-confirmation-token-valid
            security: false
            anonymous: true
        chnage-password:
            pattern: ^/api/users/change-password
            security: false
            anonymous: true
        request-password-reset:
            pattern: ^/api/users/request-password-reset
            security: false
            anonymous: true
        refresh:
            pattern:  ^/api/users/refreshToken
            stateless: true
            anonymous: true
        login:
            pattern:  ^/api/users/getToken
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /api/users/getToken
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:  ^/api
            stateless: true
            anonymous: true
            switch_user: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    encoders:
        App\Entity\User:
            algorithm: sha512
        #            algorithm: argon2i
        #            algorithm: auto

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/login-check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/is-confirmation-token-valid, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/user-email-confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/getToken, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
