services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Context\:
        resource: '../tests/Context/*'

    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'
