name: quality assurance

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      APP_ENVIRONMENT: test
      JWT_PASSPHRASE: IamYourBelovedHeroOfTheUniverse
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "xdebug"
          php-version: "8.1"
          extensions: zip
          tools: composer
          ini-values: error_reporting=-1, display_errors=On
      - name: Set env variables from .env.dist file
        run: |
          export $(grep -v '^#' .env | xargs -d '\n')
      - name: Install dependencies
        run: |
          cd web && composer install --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Prepare folders and environment
        run: |
          cd web
          composer compile-test
          mkdir -p var/log/qa-report
          mkdir -p public/images/screenshots var/log/qa-report/screenshots
      - name: Run phpcs
        run: |
          cd web && vendor/bin/phpcs --colors --report=checkstyle src tests > ./var/log/qa-report/phpcs.xml
      - name: Run phpstan
        run: |
          cd web && vendor/bin/phpstan analyse --error-format=checkstyle --ansi --no-progress > ./var/log/qa-report/phpstan.xml
      - name: Run phpunit
        run: |
          cd web && vendor/bin/phpunit --colors --testdox-html ./var/log/qa-report/testdox.html --testdox-text ./var/log/qa-report/testdox.txt
      - name: Run behat
        run: |
          cd web && vendor/bin/behat --colors --format=pretty --out std --format=junit --out ./var/log/qa-report
      - name: Copy images of behat to log folder for archiving of log artifacts
        run: |
          cd web && cp -R public/images/screenshots/* var/log/qa-report/screenshots/
      - name: Run security-checker
        run: |
          cd web && vendor/bin/security-checker security:check --format=json > ./var/log/qa-report/security-checker.json
      - name: Archive logs artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs_php-${{ matrix.php }}
          path: |
            web/var/log/qa-report
            web/var/log
            logs
