nodeLinker: node-modules

packageExtensions:
  "@vueuse/components@10.11.0":
    peerDependencies:
      vue: ^2.7.0
  "@vueuse/core@10.11.0":
    peerDependencies:
      vue: ^2.7.0
  "@vueuse/shared@10.11.0":
    peerDependencies:
      vue: ^2.7.0
  bootstrap-vue@2.23.1:
    peerDependencies:
      jquery: "*"
      vue: ^2.7.0
  portal-vue@2.1.7:
    peerDependencies:
      vue: ^2.7.0
