/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCol: typeof import('vuetify/lib')['VCol']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel']
    VExpansionPanelContent: typeof import('vuetify/lib')['VExpansionPanelContent']
    VExpansionPanelHeader: typeof import('vuetify/lib')['VExpansionPanelHeader']
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VOverflowBtn: typeof import('vuetify/lib')['VOverflowBtn']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VRadio: typeof import('vuetify/lib')['VRadio']
    VRadioGroup: typeof import('vuetify/lib')['VRadioGroup']
    VRow: typeof import('vuetify/lib')['VRow']
    VSkeletonLoader: typeof import('vuetify/lib')['VSkeletonLoader']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
  }
}
